---
spring:
  rabbitmq:
    addresses: rabbitmqamqp1.services.svc.cluster.local
    username: admin
    password: CH33R44


---
spring:
  rabbitmq:
    addresses: rabbitmqamqp1.services.svc.cluster.local
    username: admin
    password: CH33R44

  cloud:
    stream:
      bindings:
        input:
          binder: rabbit
          destination: input
          group: ${spring.application.name}

          consumer:
            concurrency: 10
            max-attempts: 30

      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              durableSubscription: true
              requeueRejected: true
              republishToDlq: true
              transacted: true
