---
spring:
  rabbitmq:
    addresses: rabbitmqamqp1.services.svc.cluster.local
    username: admin
    password: CH33R44

  cloud:
    stream:
      bindings:
        input:
          binder: rabbit
          destination: input
          group: ${spring.application.name}

          consumer:
            concurrency: 10
            max-attempts: 3

      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              durableSubscription: true

              ## TODO: try setting to false
              requeueRejected: true

              republishToDlq: true
              transacted: true
              prefix: ha.

