---
server.port: 8800
security.basic.enabled: false
management.security.enabled: false

spring:
  rabbitmq:
    addresses: rabbitmqamqp1.services.svc.cluster.local
    username: admin
    password: CH33R44

  cloud:
    stream:
      bindings:
        input:
          binder: rabbit
          destination: test-michele
          group: ${spring.application.name}
          consumer:
            concurrency: 10
            max-attempts: 5

      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              durableSubscription: true
              requeueRejected: true
              republishToDlq: true
              prefix: ha.
              transacted: true

#debug: true
#logging:
#  level:
#    root: DEBUG

