---
server.port: 9998

spring:
  rabbitmq:
    addresses: rabbitmqamqp1.services.svc.cluster.local
    username: admin
    password: CH33R44

  cloud:
    stream:
      bindings:
        input:
          binder: rabbit
          destination: test-michele
          group: ${spring.application.name}

      rabbit:
        bindings:
          input:
            producer:
              transacted: true
              prefix: ha.
              delivery-mode: persistent
